[tool.poetry]
name = "pythonprojectgithub"
version = "0.1.0"
description = ""
authors = ["Alexandr Savitsky <savitsky.alexandr@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
